                                                                                                                                                                                             pg_get_functiondef                                                                                                                                                                                             
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_rides_universal(from_city_in text DEFAULT NULL::text, to_city_in text DEFAULT NULL::text, from_lat double precision DEFAULT NULL::double precision, from_lng double precision DEFAULT NULL::double precision, to_lat double precision DEFAULT NULL::double precision, to_lng double precision DEFAULT NULL::double precision, radius_km double precision DEFAULT 20)+
  RETURNS TABLE(ride_id uuid, driver_id text, from_city_out text, to_city_out text, from_lat_out double precision, from_lng_out double precision, to_lat_out double precision, to_lng_out double precision, departuredate timestamp without time zone, availableseats integer, priceperseat numeric, distance_from_km double precision, distance_to_km double precision, match_type text)                  +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                                         +
 AS $function$                                                                                                                                                                                                                                                                                                                                                                                             +
 BEGIN                                                                                                                                                                                                                                                                                                                                                                                                     +
     RETURN QUERY                                                                                                                                                                                                                                                                                                                                                                                          +
     SELECT                                                                                                                                                                                                                                                                                                                                                                                                +
         r.id,                                                                                                                                                                                                                                                                                                                                                                                             +
         r."driverId",                                                                                                                                                                                                                                                                                                                                                                                     +
         r."fromCity"::text AS from_city_out,                                                                                                                                                                                                                                                                                                                                                              +
         r."toCity"::text AS to_city_out,                                                                                                                                                                                                                                                                                                                                                                  +
         ST_Y(r.from_geom) AS from_lat_out,                                                                                                                                                                                                                                                                                                                                                                +
         ST_X(r.from_geom) AS from_lng_out,                                                                                                                                                                                                                                                                                                                                                                +
         ST_Y(r.to_geom) AS to_lat_out,                                                                                                                                                                                                                                                                                                                                                                    +
         ST_X(r.to_geom) AS to_lng_out,                                                                                                                                                                                                                                                                                                                                                                    +
         r."departureDate",                                                                                                                                                                                                                                                                                                                                                                                +
         r."availableSeats",                                                                                                                                                                                                                                                                                                                                                                               +
         r."pricePerSeat",                                                                                                                                                                                                                                                                                                                                                                                 +
         COALESCE(                                                                                                                                                                                                                                                                                                                                                                                         +
             CASE                                                                                                                                                                                                                                                                                                                                                                                          +
                 WHEN from_lat IS NOT NULL AND from_lng IS NOT NULL THEN                                                                                                                                                                                                                                                                                                                                   +
                     ST_Distance(                                                                                                                                                                                                                                                                                                                                                                          +
                         ST_SetSRID(ST_MakePoint(from_lng, from_lat), 4326)::geography,                                                                                                                                                                                                                                                                                                                    +
                         ST_MakeLine(r.from_geom, r.to_geom)::geography                                                                                                                                                                                                                                                                                                                                    +
                     ) / 1000                                                                                                                                                                                                                                                                                                                                                                              +
             END,                                                                                                                                                                                                                                                                                                                                                                                          +
             0                                                                                                                                                                                                                                                                                                                                                                                             +
         ) AS distance_from_km,                                                                                                                                                                                                                                                                                                                                                                            +
         COALESCE(                                                                                                                                                                                                                                                                                                                                                                                         +
             CASE                                                                                                                                                                                                                                                                                                                                                                                          +
                 WHEN to_lat IS NOT NULL AND to_lng IS NOT NULL THEN                                                                                                                                                                                                                                                                                                                                       +
                     ST_Distance(                                                                                                                                                                                                                                                                                                                                                                          +
                         ST_SetSRID(ST_MakePoint(to_lng, to_lat), 4326)::geography,                                                                                                                                                                                                                                                                                                                        +
                         ST_MakeLine(r.from_geom, r.to_geom)::geography                                                                                                                                                                                                                                                                                                                                    +
                     ) / 1000                                                                                                                                                                                                                                                                                                                                                                              +
             END,                                                                                                                                                                                                                                                                                                                                                                                          +
             0                                                                                                                                                                                                                                                                                                                                                                                             +
         ) AS distance_to_km,                                                                                                                                                                                                                                                                                                                                                                              +
         CASE                                                                                                                                                                                                                                                                                                                                                                                              +
             WHEN from_lat IS NOT NULL AND from_lng IS NOT NULL AND to_lat IS NOT NULL AND to_lng IS NOT NULL THEN 'geo_match'                                                                                                                                                                                                                                                                             +
             WHEN from_city_in IS NOT NULL OR to_city_in IS NOT NULL THEN 'city_match'                                                                                                                                                                                                                                                                                                                     +
             ELSE 'nearby_match'                                                                                                                                                                                                                                                                                                                                                                           +
         END AS match_type                                                                                                                                                                                                                                                                                                                                                                                 +
     FROM rides r                                                                                                                                                                                                                                                                                                                                                                                          +
     WHERE r."availableSeats" > 0                                                                                                                                                                                                                                                                                                                                                                          +
       AND r."departureDate" >= NOW()                                                                                                                                                                                                                                                                                                                                                                      +
       AND (                                                                                                                                                                                                                                                                                                                                                                                               +
           (from_lat IS NULL OR from_lng IS NULL OR                                                                                                                                                                                                                                                                                                                                                        +
            ST_DWithin(                                                                                                                                                                                                                                                                                                                                                                                    +
                ST_SetSRID(ST_MakePoint(from_lng, from_lat), 4326)::geography,                                                                                                                                                                                                                                                                                                                             +
                ST_MakeLine(r.from_geom, r.to_geom)::geography,                                                                                                                                                                                                                                                                                                                                            +
                radius_km * 1000                                                                                                                                                                                                                                                                                                                                                                           +
            ))                                                                                                                                                                                                                                                                                                                                                                                             +
           AND                                                                                                                                                                                                                                                                                                                                                                                             +
           (to_lat IS NULL OR to_lng IS NULL OR                                                                                                                                                                                                                                                                                                                                                            +
            ST_DWithin(                                                                                                                                                                                                                                                                                                                                                                                    +
                ST_SetSRID(ST_MakePoint(to_lng, to_lat), 4326)::geography,                                                                                                                                                                                                                                                                                                                                 +
                ST_MakeLine(r.from_geom, r.to_geom)::geography,                                                                                                                                                                                                                                                                                                                                            +
                radius_km * 1000                                                                                                                                                                                                                                                                                                                                                                           +
            ))                                                                                                                                                                                                                                                                                                                                                                                             +
       )                                                                                                                                                                                                                                                                                                                                                                                                   +
       AND (                                                                                                                                                                                                                                                                                                                                                                                               +
           (from_city_in IS NULL OR r."fromCity" ILIKE '%' || from_city_in || '%')                                                                                                                                                                                                                                                                                                                         +
           AND (to_city_in IS NULL OR r."toCity" ILIKE '%' || to_city_in || '%')                                                                                                                                                                                                                                                                                                                           +
       )                                                                                                                                                                                                                                                                                                                                                                                                   +
     ORDER BY (distance_from_km + distance_to_km) ASC                                                                                                                                                                                                                                                                                                                                                      +
     LIMIT 50;                                                                                                                                                                                                                                                                                                                                                                                             +
 END;                                                                                                                                                                                                                                                                                                                                                                                                      +
 $function$                                                                                                                                                                                                                                                                                                                                                                                                +
 
(1 row)

